print("Welcome To Info Editor")
name = input("Enter Your Name:")
lastname = input("Enter Your Last Name:")
email = input("Enter Your Email:")
password = input("Enter Your Password:")
phone = input("Enter Your Phone Number:")
print("Your Info")
print(name)
print(lastname)
print(email)
print(password)
print(phone)
print("Your Fake Info")
from faker import Faker
fake = Faker()
print(fake.name())
print(fake.email())
print(fake.password)
print("Phone Number is Not Defind")